{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grpc-enterprise-v3
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grpc-enterprise-v3
    app.kubernetes.io/name: grpc-enterprise-v3
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: grpc-enterprise-v3
{{- end }}
