apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    {{- if .Values.global.istio.enabled }}
    istio-injection: enabled
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
