{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app: secure-distributed
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  config-user: {{ .Values.secrets.configUser | quote }}
  config-password: {{ .Values.secrets.configPassword | quote }}
  eureka-user: {{ .Values.secrets.eurekaUser | quote }}
  eureka-password: {{ .Values.secrets.eurekaPassword | quote }}
{{- end }}
