apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: secure-distributed
  labels:
    app: secure-distributed
type: Opaque
data:
  jwt-secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  config-user: Y29uZmlnLXVzZXI=
  config-password: Y29uZmlnLXBhc3M=
  eureka-user: ZXVyZWth
  eureka-password: ZXVyZWth
