apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- if .Values.global.istio.enabled }}
    istio-injection: enabled
    {{- end }}
    app.kubernetes.io/part-of: grpc-enterprise
    app.kubernetes.io/managed-by: {{ .Release.Service }}
