apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: userservice
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z userservice-eks-redis.90ltcd.ng.0001.use1.cache.amazonaws.com 6379; do echo "Waiting for ElastiCache Redis..."; sleep 5; done']
        - name: wait-for-eureka
          image: busybox:1.36
          command: ['sh', '-c', 'until wget -qO- http://eureka-server:8761/actuator/health 2>&1 | grep -q "UP"; do echo "Waiting for eureka-server..."; sleep 5; done']
      containers:
        - name: product-service
          image: 932888576933.dkr.ecr.us-east-1.amazonaws.com/userservice/product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_CLOUD_CONFIG_USERNAME
              value: "config-user"
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              value: "config-pass"
            - name: SPRING_REDIS_HOST
              value: "userservice-eks-redis.90ltcd.ng.0001.use1.cache.amazonaws.com"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka:eureka@eureka-server:8761/eureka"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx400m -Xms128m"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: userservice
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8083
      targetPort: 8083
