apiVersion: v1
kind: Secret
metadata:
  name: userservice-secrets
  namespace: userservice
type: Opaque
stringData:
  jwt-secret: "mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890"
  enterprise-jwt-secret: "enterpriseGrpcSecretKeyForJWT256bitMinimumLength!"
  config-username: "config-user"
  config-password: "config-pass"
  eureka-username: "eureka"
  eureka-password: "eureka"
  db-username: "postgres"
  db-password: "postgres"
